"""The Alembic migrations must stay in sync with the ORM models."""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from realestate.config import get_settings

PROJECT_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture
def alembic_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Config:
    db_url = f"sqlite+pysqlite:///{(tmp_path / 'migrations.db').as_posix()}"
    monkeypatch.setenv("RE_DATABASE_URL", db_url)
    get_settings.cache_clear()
    monkeypatch.chdir(PROJECT_ROOT)
    yield Config(str(PROJECT_ROOT / "alembic.ini"))
    get_settings.cache_clear()


def test_upgrade_creates_all_tables(alembic_config: Config) -> None:
    command.upgrade(alembic_config, "head")
    engine = create_engine(get_settings().database_url)
    tables = set(inspect(engine).get_table_names())
    engine.dispose()
    assert {"listings", "listing_price_history", "scrape_runs"} <= tables


def test_no_pending_model_changes(alembic_config: Config) -> None:
    command.upgrade(alembic_config, "head")
    # alembic.command.check raises AutogenerateDiffsDetected if models drifted.
    command.check(alembic_config)
