"""initial schema

Revision ID: 32b561e4476c
Revises: 
Create Date: 2026-08-27 19:32:25.639120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b561e4476c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expose_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('living_area_sqm', sa.Float(), nullable=True),
    sa.Column('plot_area_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=64), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('heating_type', sa.String(length=64), nullable=True),
    sa.Column('energy_efficiency_class', sa.String(length=8), nullable=True),
    sa.Column('energy_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_garden', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_cellar', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('is_barrier_free', sa.Boolean(), nullable=True),
    sa.Column('listing_status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_city'), ['city'], unique=False)
        batch_op.create_index('ix_listings_city_price', ['city', 'price_eur'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_expose_id'), ['expose_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index('ix_listings_status_last_seen', ['listing_status', 'last_seen_at'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('exposes_seen', sa.Integer(), nullable=False),
    sa.Column('listings_new', sa.Integer(), nullable=False),
    sa.Column('listings_updated', sa.Integer(), nullable=False),
    sa.Column('price_changes', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('expose_id', sa.String(length=32), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_price_history_expose_id'), ['expose_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_price_history_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index('ix_price_history_listing_observed', ['listing_id', 'observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_listing_observed')
        batch_op.drop_index(batch_op.f('ix_listing_price_history_listing_id'))
        batch_op.drop_index(batch_op.f('ix_listing_price_history_expose_id'))

    op.drop_table('listing_price_history')
    op.drop_table('scrape_runs')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_status_last_seen')
        batch_op.drop_index(batch_op.f('ix_listings_postal_code'))
        batch_op.drop_index(batch_op.f('ix_listings_expose_id'))
        batch_op.drop_index('ix_listings_city_price')
        batch_op.drop_index(batch_op.f('ix_listings_city'))

    op.drop_table('listings')
    # ### end Alembic commands ###
