"""widen expose_id to 40 chars

Revision ID: e01d7e65d311
Revises: 32b561e4476c
Create Date: 2026-09-13 00:31:12.993021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01d7e65d311'
down_revision: Union[str, Sequence[str], None] = '32b561e4476c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_price_history', schema=None) as batch_op:
        batch_op.alter_column('expose_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('expose_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('expose_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('listing_price_history', schema=None) as batch_op:
        batch_op.alter_column('expose_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
